env:
  TARGET_PR_BRANCH: "test"
  PR_BRANCH_PREFIX: "dev-test"

name: PR for test branch
on:
  push:
    branches:
      - dev
jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - uses: actions/checkout@v3
      with:
        fetch-depth: 2
      - run: |
          git config user.name github-actions
          git remote update
          git fetch --all
          git checkout -b "$PR_BRANCH_PREFIX"${{ github.run_id }} origin/"$TARGET_PR_BRANCH"
          echo $(git diff)
          git cherry-pick "${GITHUB_SHA}"
          echo $(git diff)
          git push -u origin "$PR_BRANCH_PREFIX"${{ github.run_id }}
          hub pull-request -b "$TARGET_PR_BRANCH" -h "${PR_BRANCH_PREFIX}" -a "${GITHUB_ACTOR}" -m "\"AUTO: TEMP\""
