on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: run number with offset
    env:
      NUM: ${{ github.run_number }}
      run: |
        echo ::set-env name=GITHUB_RUN_NUMBER_WITH_OFFSET::$(($NUM+200))
        echo ${{ github.run_number }}
        echo $GITHUB_RUN_NUMBER_WITH_OFFSET
