on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: run number with offset
      env:
        NUM: ${{ github.run_number }}
        NUMTWO: $github.run_number + 1
      run: |
        echo $NUM
        echo $NUMTWO
