env:
  TARGET_PR_BRANCH: "test"
  PR_BRANCH_PREFIX: "dev2test"

name: PR for test branch
on:
  push:
    branches:
      - dev
jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Elevate a Cherry-Picked pull request
        run: |
          git config user.name github-actions
          git remote update
          git fetch --all
          git checkout -b "$PR_BRANCH_PREFIX"${{ github.run_id }} origin/"$TARGET_PR_BRANCH"
          git cherry-pick "${GITHUB_SHA}"
          git push -u origin "$PR_BRANCH_PREFIX"${{ github.run_id }}
          hub pull-request -b "$TARGET_PR_BRANCH" -h "$PR_BRANCH_PREFIX"${{ github.run_id }} -a "${GITHUB_ACTOR}" -m "\"AUTO: TEMP\""
  



      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 2
      #     token: ${{ secrets.TOKEN }}
      # - name: Install hub
      #     uses: geertvdc/setup-hub@master
      # - name: run hub commands
      #     env:
      #       GITHUB_USER: ${{ secrets.ACC }}
      #       GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #     run: |
      #       git config user.email ""
      #       git config user.name github-actions
      #       git remote update
      #       git fetch --all
      #       git checkout -b "$PR_BRANCH_PREFIX"${{ github.run_id }} origin/"$TARGET_PR_BRANCH"
      #       git cherry-pick "${GITHUB_SHA}"
      #       echo 0
      #       git push -u origin "$PR_BRANCH_PREFIX"${{ github.run_id }}
      #       echo 1
      #       hub release
      #       echo 2
      #       hub pull-request -b "$TARGET_PR_BRANCH" -h "${PR_BRANCH_PREFIX}" -a "${GITHUB_ACTOR}" -m "\"AUTO: TEMP\""
      #       echo 3


# env:
#   TARGET_PR_BRANCH: "test"
#   PR_BRANCH_PREFIX: "dev2test"

# name: PR for test branch
# on:
#   push:
#     branches:
#       - dev
# jobs:
#   release_pull_request:
#     runs-on: ubuntu-latest
#     name: release_pull_request
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 2
#           token: ${{ secrets.TOKEN }}
#         env:
#           GITHUB_USER: ${{ secrets.ACC }}
#           GITHUB_TOKEN: ${{ secrets.TOKEN }}
#       - run: |
#           git config user.email ""
#           git config user.name github-actions
#           git remote update
#           git fetch --all
#           git checkout -b "$PR_BRANCH_PREFIX"${{ github.run_id }} origin/"$TARGET_PR_BRANCH"
#           git cherry-pick "${GITHUB_SHA}"
#           echo 0
#           git push -u origin "$PR_BRANCH_PREFIX"${{ github.run_id }}
#           echo 1
#           hub release
#           echo 2
#           hub pull-request -b "$TARGET_PR_BRANCH" -h "${PR_BRANCH_PREFIX}" -a "${GITHUB_ACTOR}" -m "\"AUTO: TEMP\""
#           echo 3
